version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend


  backend:
    build:
      context: expressBackend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
        - PORT=3001
    command: npm start
    depends_on:
      - db


  db:
    image: postgres:13
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local